struktur tabel olah_absensi 

"Field"	"Type"	"Null"	"Key"	"Default"	"Extra"
"perner"	"varchar(50)"	"NO"	"PRI"	\N	""
"tanggal"	"date"	"NO"	"PRI"	\N	""
"jenis_hari"	"varchar(50)"	"YES"	""	\N	""
"is_jumat"	"varchar(50)"	"YES"	""	\N	""
"nama_hari"	"varchar(50)"	"YES"	""	\N	""
"jenis_hari_realisasi"	"varchar(50)"	"YES"	""	\N	""
"daily_in"	"time"	"YES"	""	\N	""
"daily_out"	"time"	"YES"	""	\N	""
"daily_in_cleansing"	"time"	"YES"	""	\N	""
"daily_out_cleansing"	"time"	"YES"	""	\N	""
"daily_in_default"	"time"	"YES"	""	\N	""
"daily_out_default"	"time"	"YES"	""	\N	""
"correction_in"	"char(50)"	"YES"	""	\N	""
"correction_out"	"char(50)"	"YES"	""	\N	""
"att_daily"	"varchar(255)"	"YES"	""	\N	""
"abs_daily"	"varchar(255)"	"YES"	""	\N	""
"att_sap"	"varchar(255)"	"YES"	""	\N	""
"abs_sap"	"varchar(255)"	"YES"	""	\N	""
"sppd_umum"	"varchar(255)"	"YES"	""	\N	""
"ws_rule"	"varchar(255)"	"YES"	""	\N	""
"jenis_jam_kerja_shift_daily"	"varchar(255)"	"YES"	""	\N	""
"jenis_jam_kerja_shift_sap"	"varchar(255)"	"YES"	""	\N	""
"status_ganda_att_abs"	"varchar(50)"	"YES"	"MUL"	\N	""
"status_ganda_ws_rule"	"varchar(50)"	"YES"	""	\N	""
"att_daily_new"	"varchar(255)"	"YES"	""	\N	""
"abs_daily_new"	"varchar(255)"	"YES"	""	\N	""
"att_sap_new"	"varchar(255)"	"YES"	""	\N	""
"abs_sap_new"	"varchar(255)"	"YES"	""	\N	""
"sppd_umum_new"	"varchar(255)"	"YES"	""	\N	""
"value_att_abs"	"varchar(500)"	"YES"	""	\N	""
"is_att_abs"	"varchar(50)"	"YES"	""	\N	""
"jenis_jam_kerja_shift_daily_new"	"varchar(50)"	"YES"	""	\N	""
"jenis_jam_kerja_shift_sap_new"	"varchar(50)"	"YES"	""	\N	""
"value_shift_daily_sap"	"varchar(500)"	"YES"	"MUL"	\N	""
"status_jam_kerja"	"varchar(50)"	"YES"	""	\N	""
"is_shift_daily_sap"	"varchar(50)"	"YES"	""	\N	""
"kategori_jam_kerja"	"varchar(50)"	"YES"	""	\N	""
"komponen_perhitungan_jkp"	"varchar(50)"	"YES"	"MUL"	\N	""
"status_absen"	"varchar(50)"	"YES"	""	\N	""
"status_in_out"	"varchar(50)"	"YES"	""	\N	""
"ket_in_out"	"varchar(50)"	"YES"	""	\N	""
"keterangan_kehadiran"	"varchar(50)"	"YES"	"MUL"	\N	""
"kategori_hit_jkp"	"varchar(50)"	"YES"	""	\N	""
"jam_kerja_pegawai"	"char(50)"	"YES"	""	\N	""
"jam_kerja_pegawai_cleansing"	"char(50)"	"YES"	""	\N	""
"jam_kerja_seharusnya"	"char(50)"	"YES"	""	\N	""
"persentase"	"char(50)"	"YES"	""	\N	""


================================================================================


struktur tabel rekap_absensi : 


"Field"	"Type"	"Null"	"Key"	"Default"	"Extra"
"PERNER"	"varchar(20)"	"NO"	"PRI"	\N	""
"NAMA"	"varchar(20)"	"NO"	""	\N	""
"BIDANG_UNIT"	"varchar(20)"	"NO"	""	\N	""
"TOTAL_HARI_REGULER"	"int"	"YES"	""	"0"	""
"HARI_KERJA_REGULER"	"int"	"YES"	""	"0"	""
"HARI_LIBUR_REGULER"	"int"	"YES"	""	"0"	""
"TOTAL_HARI_REALISASI"	"int"	"YES"	""	"0"	""
"HARI_KERJA_REALISASI"	"int"	"YES"	""	"0"	""
"HARI_LIBUR_REALISASI"	"int"	"YES"	""	"0"	""
"TOTAL_HARI_TANPA_KOREKSI"	"int"	"YES"	""	"0"	""
"TOTAL_HARI_KOREKSI"	"int"	"YES"	""	"0"	""
"KOREKSI_IN"	"int"	"YES"	""	"0"	""
"KOREKSI_OUT"	"int"	"YES"	""	"0"	""
"KOREKSI_IN_OUT"	"int"	"YES"	""	"0"	""
"TOTAL_JAM_KERJA_NORMAL"	"int"	"YES"	""	"0"	""
"PIKET"	"int"	"YES"	""	"0"	""
"PDKB"	"int"	"YES"	""	"0"	""
"REGULER"	"int"	"YES"	""	"0"	""
"TOTAL_JAM_KERJA_SHIFT"	"int"	"YES"	""	"0"	""
"SHIFT_PAGI"	"int"	"YES"	""	"0"	""
"SHIFT_SIANG"	"int"	"YES"	""	"0"	""
"SHIFT_MALAM"	"int"	"YES"	""	"0"	""
"SHIFT_OFF"	"int"	"YES"	""	"0"	""
"ABSEN_LENGKAP"	"int"	"YES"	""	"0"	""
"ABSEN_TIDAK_LENGKAP"	"int"	"YES"	""	"0"	""
"IN_OUT_KOSONG"	"int"	"YES"	""	"0"	""
"IN_KOSONG"	"int"	"YES"	""	"0"	""
"OUT_KOSONG"	"int"	"YES"	""	"0"	""
"SPPD_TUGAS_LUAR_DLL"	"int"	"YES"	""	"0"	""
"CUTI_IJIN"	"int"	"YES"	""	"0"	""
"JAM_REALISASI"	"decimal(10,2)"	"YES"	""	"0.00"	""
"JAM_SEHARUSNYA"	"decimal(10,2)"	"YES"	""	"0.00"	""
"PERSENTASE_JKP"	"decimal(5,2)"	"YES"	""	"0.00"	""
"RESULT_BLASTING"	"char(50)"	"YES"	""	\N	""
